theme = "kanagawa"

[editor]
auto-save = false
bufferline = "multiple"
color-modes = true
completion-replace = false
idle-timeout = 300
rulers = []
shell = ["fish", "-c"]
popup-border = "all"

[editor.lsp]
display-messages = true

[editor.soft-wrap]
enable = true

[editor.statusline]
right = ["primary-selection-length", "diagnostics", "version-control", "position", "file-encoding"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true

[keys.normal]
x = "select_line_below"
X = "select_line_above"

[keys.normal.space]
o = ":pipe-to kitten @ --password-file ~/.config/kitty/rc-pass launch --cwd=\"$(pwd)\" --type=window --window-title=Fsi dotnet fsi"
t = [
  ":pipe-to kitten @ --password-file ~/.config/kitty/rc-pass send-text --match='title:^Fsi' --stdin",
  ":pipe-to kitten @ --password-file ~/.config/kitty/rc-pass send-text --match='title:^Fsi' ';;\\n'"
]

[keys.select]
x = "select_line_below"
X = "select_line_above"
