[language-server]
fsharp-ls = { command = "fsautocomplete", config = { AutomaticWorkspaceInit = true } }
typescript-ls = { command = "typescript-language-server", args = ["--stdio"], config.hostInfo = "helix" }
tailwind-ls = { command = "tailwindcss-language-server", args = ["--stdio"] }

[language-server.eslint-ls]
command = "eslint-language-server"
args = ["--stdio"]

# Even though the eslint config values should have default values
# the lsp does not work unless these values are present in the config
[language-server.eslint-ls.config]
validate = "on"
experimental = { }
rulesCustomizations = []
run = "onType"
problems = { }
# nodePath configures the directory in which the eslint server should start its node_modules resolution.
# This path is relative to the workspace folder (root dir) of the server instance.
nodePath = ""
codeAction = { disableRuleComment = { enable = true }, showDocumentation = { enable = true }}

[[language]]
name = "html"
formatter = { command = "npx", args = ["--no-install", "prettier", "--parser", "html"] }

[[language]]
name = "json"
formatter = { command = "npx", args = ["--no-install", "prettier", "--parser", "json"] }

[[language]]
name = "css"
formatter = { command = "npx", args = ["--no-install", "prettier", "--parser", "css"] }

[[language]]
name = "markdown"
formatter = { command = "npx", args = ["--no-install", "prettier", "--parser", "markdown"] }
auto-format = true

[[language]]
name = "javascript"
formatter = { command = "npx", args = ["--no-install", "prettier", "--parser", "typescript"] }
auto-format = true
language-servers = [
  { name = "typescript-ls" },
  { name = "eslint-ls" }
]

[[language]]
name = "typescript"
formatter = { command = "npx", args = ["--no-install", "prettier", "--parser", "typescript"] }
auto-format = true
language-servers = [
  { name = "typescript-ls" },
  { name = "eslint-ls" }
]

[[language]]
name = "tsx"
formatter = { command = "npx", args = ["--no-install", "prettier", "--parser", "typescript"] }
auto-format = true
language-servers = [
  { name = "typescript-ls" },
  { name = "eslint-ls" },
  { name = "tailwind-ls" }
]

[[language]]
name = "fsharp"
auto-format = true
language-servers = ["fsharp-ls"]

[[grammar]]
name = "fsharp"
source = { git = "https://github.com/ionide/tree-sitter-fsharp", rev = "996ea9982bd4e490029f84682016b6793940113b" }
